# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aom', '0002_auto_20170928_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aomappserver',
            options={'managed': False, 'permissions': (('views_aomappserver_list', '查看学员信息表'), ('views_aomappserver_info', '查看学员详细信息'))},
        ),
    ]
