# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-28 05:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aom', '0003_auto_20170928_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aomappserver',
            options={'managed': False},
        ),
    ]
